apiVersion: v1
kind: Service
metadata:
  name: drone-app-notify-service
spec:
  type: NodePort
  selector:
    app: drone-app-notify
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-app-notify-deployment
  labels:
    app: drone-app-notify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-app-notify
  template:
    metadata:
      labels:
        app: drone-app-notify
    spec:
      containers:
        - name: drone-app-notify
          image: evandroborzi/drone-app-notify:v1
          imagePullPolicy: Always
          env:
          - name: "smtp_user"
            value: "teste@gmail.com"
          - name: "smtp_pwd"
            value: "teste@gmail.com"
          ports:
            - containerPort: 8070